
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/workspace/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/workspace
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
